# Generated by Django 5.1.2 on 2024-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
