# Generated by Django 5.1.2 on 2024-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(null=True, upload_to='picture_book'),
        ),
    ]
